import { ThemeColor } from './types';

export const PRESET_COLORS: Record<string, string> = {
  indigo: '#4f46e5',
  emerald: '#10b981',
  rose: '#f43f5e',
  amber: '#f59e0b',
};

export const THEME_MAP: Record<ThemeColor, string> = {
  indigo: 'bg-indigo-600 shadow-indigo-200 text-indigo-600 dark:text-indigo-400',
  emerald: 'bg-emerald-600 shadow-emerald-200 text-emerald-600 dark:text-emerald-400',
  rose: 'bg-rose-600 shadow-rose-200 text-rose-600 dark:text-rose-400',
  amber: 'bg-amber-600 shadow-amber-200 text-amber-600 dark:text-amber-400',
  custom: 'bg-[var(--theme-color)] shadow-gray-200 text-[var(--theme-color)] dark:text-[var(--theme-color)]',
};

export const THEME_GRADIENT: Record<ThemeColor, string> = {
  indigo: 'from-indigo-600 to-violet-700',
  emerald: 'from-emerald-600 to-teal-700',
  rose: 'from-rose-600 to-pink-700',
  amber: 'from-amber-600 to-orange-700',
  custom: 'from-[var(--theme-color)] to-black/30',
};

export const LOAN_STATUS_LABELS = {
  PENDING: 'বাকি',
  PAID: 'পরিশোধিত',
  RECEIVED: 'গৃহীত'
};

export const translations: any = {
  bn: {
    appTitle: 'আমার খাতা',
    diaryTitle: 'আমার ডিজিটাল ডায়েরি',
    home: 'হোম',
    history: 'হিসাব',
    summary: 'সংক্ষিপ্ত',
    reports: 'রিপোর্ট',
    settings: 'সেটিং',
    currentBalance: 'বর্তমান ব্যালেন্স',
    totalIncome: 'মোট আয়',
    totalExpense: 'মোট ব্যয়',
    todayIncome: 'আজকের আয়',
    todayExpense: 'আজকের ব্যয়',
    loanGiven: 'পাওনা টাকা',
    loanTaken: 'ধার নেওয়া',
    recentHistory: 'সাম্প্রতিক হিসাব',
    seeAll: 'সব দেখুন',
    language: 'অ্যাপের ভাষা',
    devProfile: 'ডেভেলপার পরিচিতি',
    usageGuide: 'ব্যবহার বিধি',
    backup: 'ব্যাকআপ ডাউনলোড',
    restore: 'ব্যাকআপ রিস্টোর',
    themeColor: 'থিম কালার',
    reminder: 'লোন রিমাইন্ডার',
    save: 'সংরক্ষণ করুন',
    update: 'আপডেট করুন',
    addEntry: 'হিসাব যোগ করুন',
    editEntry: 'হিসাব সংশোধন',
    monthlyNote: 'নোটস',
    devName: 'মো: মাজিদুল হাসান {শাহীন}',
    close: 'বন্ধ করুন',
    monthlySummary: 'মাসিক সারসংক্ষেপ',
    balance: 'অবশিষ্ট',
    netBalance: 'নিট ব্যালেন্স',
    weekly: 'সাপ্তাহিক',
    monthly: 'মাসিক',
    yearly: 'বাৎসরিক',
    customRange: 'কাস্টম',
    category: 'ক্যাটাগরি',
    manageCategories: 'ক্যাটাগরি ম্যানেজ',
    startDate: 'শুরুর তারিখ',
    endDate: 'শেষ তারিখ',
    allCategories: 'সব ক্যাটাগরি',
    stats: 'পরিসংখ্যান',
    finance: 'আয়-ব্যয়',
    loans: 'লেনদেন',
    netLoan: 'নিট ঋণ',
    confirmDelete: 'আপনি কি নিশ্চিত?',
    deleteWarn: 'এই হিসাবটি ডিলেট করলে আর ফিরে পাওয়া যাবে না।',
    deleteBtn: 'হ্যাঁ, ডিলেট করুন',
    cancelBtn: 'না, থাক',
    noteDetails: 'বিস্তারিত তথ্য',
    transactionNotes: 'নোটসমূহ',
    dateLabel: 'তারিখ',
    typeLabel: 'ধরণ',
    incomeType: 'আয়',
    expenseType: 'ব্যয়',
    loanTakenType: 'ধার গ্রহণ',
    loanGivenType: 'ধার প্রদান',
    closingBalance: 'সমাপনী ব্যালেন্স',
    settle: 'পরিশোধ সম্পন্ন',
    confirmSettle: 'পরিশোধ নিশ্চিত করুন',
    settleWarn: 'আপনি কি এই লেনদেনটি সম্পন্ন হিসেবে মার্ক করতে চান? এটি আপনার পেন্ডিং লিস্ট থেকে সরে যাবে।',
    yesSettle: 'হ্যাঁ, পরিশোধ হয়েছে',
    addPayment: 'পেমেন্ট যোগ করুন',
    editPayment: 'পেমেন্ট সংশোধন',
    remaining: 'অবশিষ্ট',
    paidAmount: 'পরিশোধিত',
    paymentHistory: 'পেমেন্ট হিস্ট্রি',
    editCat: 'ক্যাটাগরি এডিট',
    deleteCat: 'ক্যাটাগরি ডিলেট',
    selectCatError: 'দয়া করে একটি ক্যাটাগরি সিলেক্ট করুন',
    settledFilter: 'পরিশোধিত',
    paidStamp: 'পরিশোধিত'
  },
  en: {
    appTitle: 'Amar Khata',
    diaryTitle: 'My Digital Diary',
    home: 'Home',
    history: 'History',
    summary: 'Summary',
    reports: 'Reports',
    settings: 'Settings',
    currentBalance: 'Current Balance',
    totalIncome: 'Total Income',
    totalExpense: 'Total Expense',
    todayIncome: 'Today Income',
    todayExpense: 'Today Expense',
    loanGiven: 'Money Owed',
    loanTaken: 'Money Borrowed',
    recentHistory: 'Recent Transactions',
    seeAll: 'See All',
    language: 'App Language',
    devProfile: 'Developer Profile',
    usageGuide: 'Usage Guide',
    backup: 'Download Backup',
    restore: 'Restore Backup',
    themeColor: 'Theme Color',
    reminder: 'Loan Reminder',
    save: 'Save Changes',
    update: 'Update Entry',
    addEntry: 'Add Entry',
    editEntry: 'Edit Entry',
    monthlyNote: 'Notes',
    devName: 'Md. Majidul Hasan {Shahin}',
    close: 'Close',
    monthlySummary: 'Monthly Summary',
    balance: 'Balance',
    netBalance: 'Net Balance',
    weekly: 'Weekly',
    monthly: 'Monthly',
    yearly: 'Yearly',
    customRange: 'Custom',
    category: 'Category',
    manageCategories: 'Manage Categories',
    startDate: 'Start Date',
    endDate: 'End Date',
    allCategories: 'All Categories',
    stats: 'Statistics',
    finance: 'Finance',
    loans: 'Dealings',
    netLoan: 'Net Loan',
    confirmDelete: 'Are you sure?',
    deleteWarn: 'If you delete this record, it cannot be recovered.',
    deleteBtn: 'Yes, Delete',
    cancelBtn: 'No, Keep',
    noteDetails: 'Detailed Info',
    transactionNotes: 'Notes',
    dateLabel: 'Date',
    typeLabel: 'Type',
    incomeType: 'Income',
    expenseType: 'Expense',
    loanTakenType: 'Loan Taken',
    loanGivenType: 'Loan Given',
    closingBalance: 'Closing Balance',
    settle: 'Mark Settle',
    confirmSettle: 'Confirm Settlement',
    settleWarn: 'Are you sure you want to mark this transaction as settled? It will be moved from your pending list.',
    yesSettle: 'Yes, Settle Now',
    addPayment: 'Add Payment',
    editPayment: 'Edit Payment',
    remaining: 'Remaining',
    paidAmount: 'Paid',
    paymentHistory: 'Payment History',
    editCat: 'Edit Category',
    deleteCat: 'Delete Category',
    selectCatError: 'Please select a category',
    settledFilter: 'Settled',
    paidStamp: 'PAID'
  }
};
